import { useState, useCallback, useRef } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

const Counter = () => {
  const [tasks, setTasks] = useState<string[]>([]);
  const inputRef = useRef<HTMLInputElement>(null);
  const onButtonClick = useCallback(() => {
    if (inputRef.current) {
      setTasks([...tasks, inputRef.current.value])
    }
  }, [tasks, inputRef]);

  return (
    <>
      <div>
        <input ref={inputRef} type="text" />
        <button type="button" onClick={onButtonClick}>
          Add
        </button>        
      </div>
      <h1>Things to Do</h1>
      {tasks.length ? (
      <ol type="i">
        {tasks.map(text => (
          <li key={text}>{text}</li>
        ))}
      </ol>
      ) : (
        <div>Nothing to do.</div>
      )} 



    </>
  )
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Counter />
    </>
  )
}
